name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.PUBLIC2 }}" | docker login ghcr.io -u shatha163 --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/shatha163/week3:latest .

      - name: Push image
        run: |
          docker push ghcr.io/shatha163/week3:latest
          
      - name: Build frontend image
        run: |
          docker build -t ghcr.io/shatha163/week3-templates:latest ./templates

      - name: Push frontend image
        run: |
          docker push ghcr.io/shatha163/week3-templates:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v4 to fix the Node.js warning

      - name: Login to GHCR
        run: echo "${{ secrets.PUBLIC2 }}" | docker login ghcr.io -u shatha163 --password-stdin

      - name: Deploy to Docker
        run: |
          # 1. Move to your project directory
          cd /home/cybersecurity/Desktop/week3
          
          
          
          # 3. Restart the containers
          docker compose down 
          docker compose up -d
