name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy with docker-compose
        run: |
          cd /home/cybersecurity/Desktop/week3
          docker-compose pull
          docker-compose down
          docker-compose up -d
